import types.generateActivity
import types.generateFragments

const val inPath = "../blueprints/src/main/java/com/pascalwelsch/compositeandroid/blueprints/"

val autoGeneratedJavadocHeader = """
/**
 * This code was auto-generated by the <a href="https://github.com/passsy/CompositeAndroid">CompositeAndroid</a> generator
 *
 * @author Pascal Welsch
 */
""".trim()

fun main(args: Array<String>) {
    generateActivity()
    generateFragments()
}