package com.pascalwelsch.compositeandroid.fragment;

import android.animation.Animator;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.IntentSender;
import android.content.IntentSender.SendIntentException;
import android.content.res.Configuration;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v4.app.LoaderManager;
import android.support.v4.app.SharedElementCallback;
import android.util.AttributeSet;
import android.view.ContextMenu;
import android.view.ContextMenu.ContextMenuInfo;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.Animation;
import java.io.FileDescriptor;
import java.io.PrintWriter;

/**
 * This code was auto-generated by the <a href="https://github.com/passsy/CompositeAndroid">CompositeAndroid</a> generator
 *
 * @author Pascal Welsch
 */
public interface ICompositeFragment {


    void dump(final String prefix, final FileDescriptor fd, final PrintWriter writer, final String[] args);

    boolean getAllowEnterTransitionOverlap();

    void setAllowEnterTransitionOverlap(final boolean allow);

    boolean getAllowReturnTransitionOverlap();

    void setAllowReturnTransitionOverlap(final boolean allow);

    Context getContext();

    Object getEnterTransition();

    void setEnterTransition(@Nullable final Object transition);

    Object getExitTransition();

    void setExitTransition(@Nullable final Object transition);

    LayoutInflater getLayoutInflater(@Nullable final Bundle savedFragmentState);

    android.arch.lifecycle.Lifecycle getLifecycle();

    LoaderManager getLoaderManager();

    Object getReenterTransition();

    void setReenterTransition(@Nullable final Object transition);

    Object getReturnTransition();

    void setReturnTransition(@Nullable final Object transition);

    Object getSharedElementEnterTransition();

    void setSharedElementEnterTransition(@Nullable final Object transition);

    Object getSharedElementReturnTransition();

    void setSharedElementReturnTransition(@Nullable final Object transition);

    boolean getUserVisibleHint();

    void setUserVisibleHint(final boolean isVisibleToUser);

    View getView();

    void onActivityCreated(@Nullable final Bundle savedInstanceState);

    void onActivityResult(final int requestCode, final int resultCode, final Intent data);

    void onAttach(final Context context);

    void onAttach(final Activity activity);

    void onAttachFragment(final Fragment childFragment);

    void onConfigurationChanged(final Configuration newConfig);

    boolean onContextItemSelected(final MenuItem item);

    void onCreate(@Nullable final Bundle savedInstanceState);

    Animation onCreateAnimation(final int transit, final boolean enter, final int nextAnim);

    Animator onCreateAnimator(final int transit, final boolean enter, final int nextAnim);

    void onCreateContextMenu(final ContextMenu menu, final View v, final ContextMenuInfo menuInfo);

    void onCreateOptionsMenu(final Menu menu, final MenuInflater inflater);

    View onCreateView(@NonNull final LayoutInflater inflater, @Nullable final ViewGroup container,
            @Nullable final Bundle savedInstanceState);

    void onDestroy();

    void onDestroyOptionsMenu();

    void onDestroyView();

    void onDetach();

    LayoutInflater onGetLayoutInflater(@Nullable final Bundle savedInstanceState);

    void onHiddenChanged(final boolean hidden);

    void onInflate(final Context context, final AttributeSet attrs, final Bundle savedInstanceState);

    void onInflate(final Activity activity, final AttributeSet attrs, final Bundle savedInstanceState);

    void onLowMemory();

    void onMultiWindowModeChanged(final boolean isInMultiWindowMode);

    boolean onOptionsItemSelected(final MenuItem item);

    void onOptionsMenuClosed(final Menu menu);

    void onPause();

    void onPictureInPictureModeChanged(final boolean isInPictureInPictureMode);

    void onPrepareOptionsMenu(final Menu menu);

    void onRequestPermissionsResult(final int requestCode, @NonNull final String[] permissions,
            @NonNull final int[] grantResults);

    void onResume();

    void onSaveInstanceState(@NonNull final Bundle outState);

    void onStart();

    void onStop();

    void onViewCreated(@NonNull final View view, @Nullable final Bundle savedInstanceState);

    void onViewStateRestored(@Nullable final Bundle savedInstanceState);

    void postponeEnterTransition();

    void registerForContextMenu(final View view);

    void setArguments(@Nullable final Bundle args);

    void setEnterSharedElementCallback(final SharedElementCallback callback);

    void setExitSharedElementCallback(final SharedElementCallback callback);

    void setHasOptionsMenu(final boolean hasMenu);

    void setInitialSavedState(@Nullable final Fragment.SavedState state);

    void setMenuVisibility(final boolean menuVisible);

    void setRetainInstance(final boolean retain);

    void setTargetFragment(@Nullable final Fragment fragment, final int requestCode);

    boolean shouldShowRequestPermissionRationale(@NonNull final String permission);

    void startActivity(final Intent intent);

    void startActivity(final Intent intent, @Nullable final Bundle options);

    void startActivityForResult(final Intent intent, final int requestCode);

    void startActivityForResult(final Intent intent, final int requestCode, @Nullable final Bundle options);

    void startIntentSenderForResult(final IntentSender intent, final int requestCode,
            @Nullable final Intent fillInIntent, final int flagsMask, final int flagsValues, final int extraFlags,
            final Bundle options) throws SendIntentException;

    void startPostponedEnterTransition();

    void super_dump(final String prefix, final FileDescriptor fd, final PrintWriter writer, final String[] args);

    boolean super_getAllowEnterTransitionOverlap();

    boolean super_getAllowReturnTransitionOverlap();

    Context super_getContext();

    Object super_getEnterTransition();

    Object super_getExitTransition();

    LayoutInflater super_getLayoutInflater(@Nullable final Bundle savedFragmentState);

    android.arch.lifecycle.Lifecycle super_getLifecycle();

    LoaderManager super_getLoaderManager();

    Object super_getReenterTransition();

    Object super_getReturnTransition();

    Object super_getSharedElementEnterTransition();

    Object super_getSharedElementReturnTransition();

    boolean super_getUserVisibleHint();

    View super_getView();

    void super_onActivityCreated(@Nullable final Bundle savedInstanceState);

    void super_onActivityResult(final int requestCode, final int resultCode, final Intent data);

    void super_onAttach(final Context context);

    void super_onAttach(final Activity activity);

    void super_onAttachFragment(final Fragment childFragment);

    void super_onConfigurationChanged(final Configuration newConfig);

    boolean super_onContextItemSelected(final MenuItem item);

    void super_onCreate(@Nullable final Bundle savedInstanceState);

    Animation super_onCreateAnimation(final int transit, final boolean enter, final int nextAnim);

    Animator super_onCreateAnimator(final int transit, final boolean enter, final int nextAnim);

    void super_onCreateContextMenu(final ContextMenu menu, final View v, final ContextMenuInfo menuInfo);

    void super_onCreateOptionsMenu(final Menu menu, final MenuInflater inflater);

    View super_onCreateView(@NonNull final LayoutInflater inflater, @Nullable final ViewGroup container,
            @Nullable final Bundle savedInstanceState);

    void super_onDestroy();

    void super_onDestroyOptionsMenu();

    void super_onDestroyView();

    void super_onDetach();

    LayoutInflater super_onGetLayoutInflater(@Nullable final Bundle savedInstanceState);

    void super_onHiddenChanged(final boolean hidden);

    void super_onInflate(final Context context, final AttributeSet attrs, final Bundle savedInstanceState);

    void super_onInflate(final Activity activity, final AttributeSet attrs, final Bundle savedInstanceState);

    void super_onLowMemory();

    void super_onMultiWindowModeChanged(final boolean isInMultiWindowMode);

    boolean super_onOptionsItemSelected(final MenuItem item);

    void super_onOptionsMenuClosed(final Menu menu);

    void super_onPause();

    void super_onPictureInPictureModeChanged(final boolean isInPictureInPictureMode);

    void super_onPrepareOptionsMenu(final Menu menu);

    void super_onRequestPermissionsResult(final int requestCode, @NonNull final String[] permissions,
            @NonNull final int[] grantResults);

    void super_onResume();

    void super_onSaveInstanceState(@NonNull final Bundle outState);

    void super_onStart();

    void super_onStop();

    void super_onViewCreated(@NonNull final View view, @Nullable final Bundle savedInstanceState);

    void super_onViewStateRestored(@Nullable final Bundle savedInstanceState);

    void super_postponeEnterTransition();

    void super_registerForContextMenu(final View view);

    void super_setAllowEnterTransitionOverlap(final boolean allow);

    void super_setAllowReturnTransitionOverlap(final boolean allow);

    void super_setArguments(@Nullable final Bundle args);

    void super_setEnterSharedElementCallback(final SharedElementCallback callback);

    void super_setEnterTransition(@Nullable final Object transition);

    void super_setExitSharedElementCallback(final SharedElementCallback callback);

    void super_setExitTransition(@Nullable final Object transition);

    void super_setHasOptionsMenu(final boolean hasMenu);

    void super_setInitialSavedState(@Nullable final Fragment.SavedState state);

    void super_setMenuVisibility(final boolean menuVisible);

    void super_setReenterTransition(@Nullable final Object transition);

    void super_setRetainInstance(final boolean retain);

    void super_setReturnTransition(@Nullable final Object transition);

    void super_setSharedElementEnterTransition(@Nullable final Object transition);

    void super_setSharedElementReturnTransition(@Nullable final Object transition);

    void super_setTargetFragment(@Nullable final Fragment fragment, final int requestCode);

    void super_setUserVisibleHint(final boolean isVisibleToUser);

    boolean super_shouldShowRequestPermissionRationale(@NonNull final String permission);

    void super_startActivity(final Intent intent);

    void super_startActivity(final Intent intent, @Nullable final Bundle options);

    void super_startActivityForResult(final Intent intent, final int requestCode);

    void super_startActivityForResult(final Intent intent, final int requestCode, @Nullable final Bundle options);

    void super_startIntentSenderForResult(final IntentSender intent, final int requestCode,
            @Nullable final Intent fillInIntent, final int flagsMask, final int flagsValues, final int extraFlags,
            final Bundle options) throws SendIntentException;

    void super_startPostponedEnterTransition();

    String super_toString();

    void super_unregisterForContextMenu(final View view);

    String toString();

    void unregisterForContextMenu(final View view);
}
