package com.pascalwelsch.compositeandroid.fragment;

import android.animation.Animator;
import android.app.Activity;
import android.arch.lifecycle.LiveData;
import android.arch.lifecycle.ViewModelStore;
import android.content.Context;
import android.content.Intent;
import android.content.IntentSender;
import android.content.IntentSender.SendIntentException;
import android.content.res.Configuration;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v4.app.LoaderManager;
import android.support.v4.app.SharedElementCallback;
import android.util.AttributeSet;
import android.view.ContextMenu;
import android.view.ContextMenu.ContextMenuInfo;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.Animation;
import java.io.FileDescriptor;
import java.io.PrintWriter;

/**
 * This code was auto-generated by the <a href="https://github.com/passsy/CompositeAndroid">CompositeAndroid</a>
 * generator
 *
 * @author Pascal Welsch
 */
public interface ICompositeFragment {


    void dump(String prefix, FileDescriptor fd, PrintWriter writer, String[] args);

    boolean getAllowEnterTransitionOverlap();

    void setAllowEnterTransitionOverlap(boolean allow);

    boolean getAllowReturnTransitionOverlap();

    void setAllowReturnTransitionOverlap(boolean allow);

    Context getContext();

    Object getEnterTransition();

    void setEnterTransition(@Nullable Object transition);

    Object getExitTransition();

    void setExitTransition(@Nullable Object transition);

    LayoutInflater getLayoutInflater(@Nullable Bundle savedFragmentState);

    android.arch.lifecycle.Lifecycle getLifecycle();

    LoaderManager getLoaderManager();

    Object getReenterTransition();

    void setReenterTransition(@Nullable Object transition);

    Object getReturnTransition();

    void setReturnTransition(@Nullable Object transition);

    Object getSharedElementEnterTransition();

    void setSharedElementEnterTransition(@Nullable Object transition);

    Object getSharedElementReturnTransition();

    void setSharedElementReturnTransition(@Nullable Object transition);

    boolean getUserVisibleHint();

    void setUserVisibleHint(boolean isVisibleToUser);

    View getView();

    android.arch.lifecycle.LifecycleOwner getViewLifecycleOwner();

    LiveData<android.arch.lifecycle.LifecycleOwner> getViewLifecycleOwnerLiveData();

    ViewModelStore getViewModelStore();

    void onActivityCreated(@Nullable Bundle savedInstanceState);

    void onActivityResult(int requestCode, int resultCode, Intent data);

    void onAttach(Context context);

    void onAttach(Activity activity);

    void onAttachFragment(Fragment childFragment);

    void onConfigurationChanged(Configuration newConfig);

    boolean onContextItemSelected(MenuItem item);

    void onCreate(@Nullable Bundle savedInstanceState);

    Animation onCreateAnimation(int transit, boolean enter, int nextAnim);

    Animator onCreateAnimator(int transit, boolean enter, int nextAnim);

    void onCreateContextMenu(ContextMenu menu, View v, ContextMenuInfo menuInfo);

    void onCreateOptionsMenu(Menu menu, MenuInflater inflater);

    View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
            @Nullable Bundle savedInstanceState);

    void onDestroy();

    void onDestroyOptionsMenu();

    void onDestroyView();

    void onDetach();

    LayoutInflater onGetLayoutInflater(@Nullable Bundle savedInstanceState);

    void onHiddenChanged(boolean hidden);

    void onInflate(Context context, AttributeSet attrs, Bundle savedInstanceState);

    void onInflate(Activity activity, AttributeSet attrs, Bundle savedInstanceState);

    void onLowMemory();

    void onMultiWindowModeChanged(boolean isInMultiWindowMode);

    boolean onOptionsItemSelected(MenuItem item);

    void onOptionsMenuClosed(Menu menu);

    void onPause();

    void onPictureInPictureModeChanged(boolean isInPictureInPictureMode);

    void onPrepareOptionsMenu(Menu menu);

    void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults);

    void onResume();

    void onSaveInstanceState(@NonNull Bundle outState);

    void onStart();

    void onStop();

    void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState);

    void onViewStateRestored(@Nullable Bundle savedInstanceState);

    void postponeEnterTransition();

    void registerForContextMenu(View view);

    void setArguments(@Nullable Bundle args);

    void setEnterSharedElementCallback(SharedElementCallback callback);

    void setExitSharedElementCallback(SharedElementCallback callback);

    void setHasOptionsMenu(boolean hasMenu);

    void setInitialSavedState(@Nullable Fragment.SavedState state);

    void setMenuVisibility(boolean menuVisible);

    void setRetainInstance(boolean retain);

    void setTargetFragment(@Nullable Fragment fragment, int requestCode);

    boolean shouldShowRequestPermissionRationale(@NonNull String permission);

    void startActivity(Intent intent);

    void startActivity(Intent intent, @Nullable Bundle options);

    void startActivityForResult(Intent intent, int requestCode);

    void startActivityForResult(Intent intent, int requestCode, @Nullable Bundle options);

    void startIntentSenderForResult(IntentSender intent, int requestCode, @Nullable Intent fillInIntent,
            int flagsMask, int flagsValues, int extraFlags, Bundle options) throws SendIntentException;

    void startPostponedEnterTransition();

    void super_dump(String prefix, FileDescriptor fd, PrintWriter writer, String[] args);

    boolean super_getAllowEnterTransitionOverlap();

    boolean super_getAllowReturnTransitionOverlap();

    Context super_getContext();

    Object super_getEnterTransition();

    Object super_getExitTransition();

    LayoutInflater super_getLayoutInflater(@Nullable Bundle savedFragmentState);

    android.arch.lifecycle.Lifecycle super_getLifecycle();

    LoaderManager super_getLoaderManager();

    Object super_getReenterTransition();

    Object super_getReturnTransition();

    Object super_getSharedElementEnterTransition();

    Object super_getSharedElementReturnTransition();

    boolean super_getUserVisibleHint();

    View super_getView();

    android.arch.lifecycle.LifecycleOwner super_getViewLifecycleOwner();

    LiveData<android.arch.lifecycle.LifecycleOwner> super_getViewLifecycleOwnerLiveData();

    ViewModelStore super_getViewModelStore();

    void super_onActivityCreated(@Nullable Bundle savedInstanceState);

    void super_onActivityResult(int requestCode, int resultCode, Intent data);

    void super_onAttach(Context context);

    void super_onAttach(Activity activity);

    void super_onAttachFragment(Fragment childFragment);

    void super_onConfigurationChanged(Configuration newConfig);

    boolean super_onContextItemSelected(MenuItem item);

    void super_onCreate(@Nullable Bundle savedInstanceState);

    Animation super_onCreateAnimation(int transit, boolean enter, int nextAnim);

    Animator super_onCreateAnimator(int transit, boolean enter, int nextAnim);

    void super_onCreateContextMenu(ContextMenu menu, View v, ContextMenuInfo menuInfo);

    void super_onCreateOptionsMenu(Menu menu, MenuInflater inflater);

    View super_onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
            @Nullable Bundle savedInstanceState);

    void super_onDestroy();

    void super_onDestroyOptionsMenu();

    void super_onDestroyView();

    void super_onDetach();

    LayoutInflater super_onGetLayoutInflater(@Nullable Bundle savedInstanceState);

    void super_onHiddenChanged(boolean hidden);

    void super_onInflate(Context context, AttributeSet attrs, Bundle savedInstanceState);

    void super_onInflate(Activity activity, AttributeSet attrs, Bundle savedInstanceState);

    void super_onLowMemory();

    void super_onMultiWindowModeChanged(boolean isInMultiWindowMode);

    boolean super_onOptionsItemSelected(MenuItem item);

    void super_onOptionsMenuClosed(Menu menu);

    void super_onPause();

    void super_onPictureInPictureModeChanged(boolean isInPictureInPictureMode);

    void super_onPrepareOptionsMenu(Menu menu);

    void super_onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
            @NonNull int[] grantResults);

    void super_onResume();

    void super_onSaveInstanceState(@NonNull Bundle outState);

    void super_onStart();

    void super_onStop();

    void super_onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState);

    void super_onViewStateRestored(@Nullable Bundle savedInstanceState);

    void super_postponeEnterTransition();

    void super_registerForContextMenu(View view);

    void super_setAllowEnterTransitionOverlap(boolean allow);

    void super_setAllowReturnTransitionOverlap(boolean allow);

    void super_setArguments(@Nullable Bundle args);

    void super_setEnterSharedElementCallback(SharedElementCallback callback);

    void super_setEnterTransition(@Nullable Object transition);

    void super_setExitSharedElementCallback(SharedElementCallback callback);

    void super_setExitTransition(@Nullable Object transition);

    void super_setHasOptionsMenu(boolean hasMenu);

    void super_setInitialSavedState(@Nullable Fragment.SavedState state);

    void super_setMenuVisibility(boolean menuVisible);

    void super_setReenterTransition(@Nullable Object transition);

    void super_setRetainInstance(boolean retain);

    void super_setReturnTransition(@Nullable Object transition);

    void super_setSharedElementEnterTransition(@Nullable Object transition);

    void super_setSharedElementReturnTransition(@Nullable Object transition);

    void super_setTargetFragment(@Nullable Fragment fragment, int requestCode);

    void super_setUserVisibleHint(boolean isVisibleToUser);

    boolean super_shouldShowRequestPermissionRationale(@NonNull String permission);

    void super_startActivity(Intent intent);

    void super_startActivity(Intent intent, @Nullable Bundle options);

    void super_startActivityForResult(Intent intent, int requestCode);

    void super_startActivityForResult(Intent intent, int requestCode, @Nullable Bundle options);

    void super_startIntentSenderForResult(IntentSender intent, int requestCode, @Nullable Intent fillInIntent,
            int flagsMask, int flagsValues, int extraFlags, Bundle options) throws SendIntentException;

    void super_startPostponedEnterTransition();

    String super_toString();

    void super_unregisterForContextMenu(View view);

    String toString();

    void unregisterForContextMenu(View view);
}
