package com.pascalwelsch.compositeandroid.fragment;

import android.app.Dialog;
import android.content.Context;
import android.content.DialogInterface;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentTransaction;
import android.view.LayoutInflater;


/**
 * This code was auto-generated by the <a href="https://github.com/passsy/CompositeAndroid">CompositeAndroid</a> generator
 *
 * @author Pascal Welsch
 */
public interface ICompositeDialogFragment extends ICompositeFragment {


    void onAttach(final Context context);

    void onCreate(@Nullable final Bundle savedInstanceState);

    void onActivityCreated(final Bundle savedInstanceState);

    void onStart();

    void onStop();

    void onSaveInstanceState(final Bundle outState);

    void onDestroyView();

    void onDetach();

    void dismiss();

    void dismissAllowingStateLoss();

    Dialog getDialog();

    boolean getShowsDialog();

    void setShowsDialog(final boolean showsDialog);

    int getTheme();

    boolean isCancelable();

    void setCancelable(final boolean cancelable);

    void onCancel(final DialogInterface dialog);

    Dialog onCreateDialog(final Bundle savedInstanceState);

    void onDismiss(final DialogInterface dialog);

    LayoutInflater onGetLayoutInflater(final Bundle savedInstanceState);

    void setStyle(final int style, final int theme);

    void setupDialog(final Dialog dialog, final int style);

    void show(final FragmentManager manager, final String tag);

    int show(final FragmentTransaction transaction, final String tag);

    void super_dismiss();

    void super_dismissAllowingStateLoss();

    Dialog super_getDialog();

    boolean super_getShowsDialog();

    int super_getTheme();

    boolean super_isCancelable();

    void super_onActivityCreated(final Bundle savedInstanceState);

    void super_onAttach(final Context context);

    void super_onCancel(final DialogInterface dialog);

    void super_onCreate(@Nullable final Bundle savedInstanceState);

    Dialog super_onCreateDialog(final Bundle savedInstanceState);

    void super_onDestroyView();

    void super_onDetach();

    void super_onDismiss(final DialogInterface dialog);

    LayoutInflater super_onGetLayoutInflater(final Bundle savedInstanceState);

    void super_onSaveInstanceState(final Bundle outState);

    void super_onStart();

    void super_onStop();

    void super_setCancelable(final boolean cancelable);

    void super_setShowsDialog(final boolean showsDialog);

    void super_setStyle(final int style, final int theme);

    void super_setupDialog(final Dialog dialog, final int style);

    void super_show(final FragmentManager manager, final String tag);

    int super_show(final FragmentTransaction transaction, final String tag);
}
